(function(){'use strict';
const $=id=>document.getElementById(id),E=window.MatesEngine,C=window.StudioConfig,esc=E.esc;
const prefix='mates-estudi:'+new URL('.',document.baseURI).pathname+':';
const read=(k,def)=>{try{const v=JSON.parse(localStorage.getItem(prefix+k));return v===null?def:v;}catch(_){return def;}};
function write(k,v){try{localStorage.setItem(prefix+k,JSON.stringify(v));return true;}catch(_){toast('No s\u2019ha pogut desar: comprova l\u2019espai i els permisos del navegador.');return false;}}
let mode='eq',current=null,currentQuery=null,worker=null,job=0,timer=0,toastTimer=0,tab='saved',undo=[];
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
const modeInfo=id=>C.modes.find(m=>m.id===id)||C.modes[0];
function validQuery(raw){if(!raw||typeof raw!=='object'||!C.modes.some(m=>m.id===raw.mode)||typeof raw.expression!=='string'||raw.expression.length>450)throw new Error('Consulta no v\u00e0lida.');let q={mode:raw.mode,expression:raw.expression};for(const k of ['a','b','g','order','side','xmin','xmax'])if(raw[k]!==undefined){if(typeof raw[k]!=='string'||raw[k].length>(k==='g'?450:90))throw new Error('Par\u00e0metre no v\u00e0lid.');q[k]=raw[k];}return q;}
function cleanEntries(list,max){if(!Array.isArray(list)||list.length>max)throw new Error('Llista de consultes no v\u00e0lida.');return list.map((item,i)=>{if(!item||typeof item!=='object')throw new Error('Entrada no v\u00e0lida.');return {id:typeof item.id==='string'&&/^[a-z0-9-]+$/i.test(item.id)?item.id:Date.now()+'-'+i,query:validQuery(item.query),note:typeof item.note==='string'?item.note.slice(0,2000):'',date:typeof item.date==='string'?item.date.slice(0,40):new Date().toISOString()};});}
let saved=[],history=[];try{saved=cleanEntries(read('saved',[]),100);history=cleanEntries(read('history',[]),30);}catch(_){toast('Hi ha dades locals no v\u00e0lides. Les dades originals no s\u2019han sobreescrit.');}
const graph=new window.StudioGraph($('graph'),$('graph-legend'),$('graph-coordinates'));
const theme=read('theme','light');document.documentElement.dataset.theme=theme==='dark'?'dark':'light';
$('theme-toggle').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;write('theme',t);graph.schedule();};
function buildNav(){let group='';$('mode-nav').innerHTML=C.modes.map(m=>{let h='';if(group!==m.group){group=m.group;h='<div class="nav-group">'+({a:'\u00c0lgebra',c:'C\u00e0lcul',g:'Representaci\u00f3'})[group]+'</div>';}return h+'<button class="mode-button" data-mode="'+m.id+'"><span class="mode-mark">'+esc(m.mark)+'</span>'+esc(m.label)+'</button>';}).join('');$('mode-select').innerHTML=C.modes.map(m=>'<option value="'+m.id+'">'+esc(m.label)+'</option>').join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('mode-select').onchange=()=>setMode($('mode-select').value);}
function paramInput(key,label,value='',wide=false){return '<label class="'+(wide?'wide':'')+'">'+esc(label)+'<input id="param-'+key+'" data-param="'+key+'" value="'+esc(value)+'" spellcheck="false" maxlength="450"></label>';}
function parameters(){let h='';if(mode==='derivative'){h=paramInput('a','Tangent en x = (opcional)','')+'<label>Ordre<select id="param-order" data-param="order"><option value="1">Primera derivada</option><option value="2">Segona derivada</option></select></label>';}
 if(mode==='definite'||mode==='area'){if(mode==='area')h=paramInput('g','Segona funci\u00f3 g(x)','2x',true);h+=paramInput('a','L\u00edmit a','0')+paramInput('b','L\u00edmit b',mode==='area'?'2':'1');}
 if(mode==='limit')h=paramInput('a','x tendeix a (admet inf)','0')+'<label>Costat<select id="param-side" data-param="side"><option value="both">Tots dos</option><option value="left">Esquerre</option><option value="right">Dret</option></select></label>';
 $('parameters').innerHTML=h;
}
function setMode(id,query=null){stop();mode=modeInfo(id).id;const m=modeInfo(mode);current=null;currentQuery=null;$('result-region').hidden=true;$('empty-state').hidden=false;$('error-card').hidden=true;$('operation-name').textContent=m.label;$('expression-label').textContent=mode==='system'?'Equacions, separades per ;':mode==='area'?'Primera funci\u00f3 f(x)':'Expressi\u00f3 o equaci\u00f3';$('input-hint').textContent=m.hint;$('mode-select').value=mode;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-current',b.dataset.mode===mode?'page':'false');});parameters();
 let q=query;try{q=q||validQuery(read('draft-'+mode,{mode,expression:m.sample}));}catch(_){q={mode,expression:m.sample};}$('expression').value=q.expression||m.sample;$('expression').rows=mode==='system'?3:1;$('xmin').value=q.xmin||'-6';$('xmax').value=q.xmax||'6';for(const el of document.querySelectorAll('[data-param]'))if(q[el.dataset.param]!==undefined)el.value=q[el.dataset.param];
 const ex=C.examples.filter(x=>x.mode===mode);$('example-buttons').innerHTML='';ex.forEach(q=>{const b=document.createElement('button');b.textContent=q.label;b.title=q.expression;b.onclick=()=>{setMode(mode,{mode,...q});run();};$('example-buttons').append(b);});undo=[];preview();historyReplace();write('last-mode',mode);}
function historyReplace(){if(location.hash!=='#'+mode)window.history.replaceState(null,'','#'+mode);}
function query(){const q={mode,expression:$('expression').value.trim(),xmin:$('xmin').value.trim(),xmax:$('xmax').value.trim()};document.querySelectorAll('[data-param]').forEach(el=>q[el.dataset.param]=el.value.trim());return validQuery(q);}
function preview(){const out=$('math-preview'),s=$('expression').value;try{const lines=s.split(/[;\n]+/).filter(t=>t.trim());out.innerHTML=lines.map(line=>{const split=line.split(/(<=|>=|=|<|>|\u2264|\u2265)/);if(split.length===1)return E.math(E.parse(line,mode==='system'?['x','y','z']:['x']));if(split.length!==3)throw new Error();return E.M(E.body(E.parse(split[0],['x','y','z']))+'<mo>'+esc(split[1].replace('<=','\u2264').replace('>=','\u2265'))+'</mo>'+E.body(E.parse(split[2],['x','y','z'])));}).join('');}catch(_){out.innerHTML='<span class="invalid">La vista matem\u00e0tica apareixer\u00e0 quan l\u2019expressi\u00f3 estigui completa.</span>';}}
function changed(){current=null;$('result-region').hidden=true;$('empty-state').hidden=false;$('error-card').hidden=true;stop();preview();try{write('draft-'+mode,query());}catch(_){}}
$('expression').maxLength=450;$('solver-form').addEventListener('input',changed);$('solver-form').addEventListener('change',changed);$('expression').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||mode!=='system')){e.preventDefault();run();}});$('solver-form').onsubmit=e=>{e.preventDefault();run();};
$('clear-input').onclick=()=>{remember();$('expression').value='';changed();$('expression').focus();};
function remember(){undo.push({value:$('expression').value,start:$('expression').selectionStart,end:$('expression').selectionEnd});if(undo.length>40)undo.shift();}
const keys={basic:[['x','x'],['x\u00b2','wrap','(',')^2'],['x\u207f','power'],['a/b','fraction'],['\u221a','wrap','sqrt(',')'],['(', '('],[')',')'],['\u03c0','pi'],['=','='],['\u2264','<='],['\u232b','delete'],['\u21b6','undo']],functions:[['sin','wrap','sin(',')'],['cos','wrap','cos(',')'],['tan','wrap','tan(',')'],['ln','wrap','ln(',')'],['e\u02e3','wrap','exp(',')'],['|x|','wrap','abs(',')'],['asin','wrap','asin(',')'],['acos','wrap','acos(',')'],['atan','wrap','atan(',')'],['1/x','wrap','1/(',')'],['\u221e','inf'],['\u232b','delete']]};
function keyboard(tabName){$('key-grid').innerHTML='';keys[tabName].forEach(([name,kind,a,b])=>{const key=document.createElement('button');key.type='button';key.textContent=name;key.setAttribute('aria-label','Insereix '+name);key.addEventListener('pointerdown',e=>e.preventDefault());key.onclick=()=>insert(kind,a,b);$('key-grid').append(key);});document.querySelectorAll('[data-key-tab]').forEach(b=>b.classList.toggle('active',b.dataset.keyTab===tabName));}
function insert(kind,a,b){const el=$('expression'),start=el.selectionStart,end=el.selectionEnd,sel=el.value.slice(start,end);if(kind==='undo'){const u=undo.pop();if(u){el.value=u.value;el.setSelectionRange(u.start,u.end);}el.focus();changed();return;}remember();let text=kind,pos;
 if(kind==='delete'){if(start===end){if(start>0)el.setRangeText('',start-1,end,'end');}else el.setRangeText('',start,end,'end');}
 else{if(kind==='wrap'){text=a+sel+b;pos=sel?start+text.length:start+a.length;}if(kind==='power'){text=(sel?'('+sel+')':'x')+'^()';pos=start+text.length-1;}if(kind==='fraction'){text='('+(sel||'')+')/()';pos=sel?start+text.length-1:start+1;}el.setRangeText(text,start,end,'end');if(pos!==undefined)el.setSelectionRange(pos,pos);}
 el.focus();changed();}
$('toggle-keyboard').onclick=()=>{const hidden=!$('keyboard').hidden;$('keyboard').hidden=hidden;$('toggle-keyboard').setAttribute('aria-expanded',String(!hidden));};document.querySelectorAll('[data-key-tab]').forEach(b=>b.onclick=()=>keyboard(b.dataset.keyTab));
function busy(b){$('solve-button').disabled=b;$('solve-button').innerHTML=b?'Calculant\u2026':'Resoldre <span>\u2192</span>';$('cancel-solve').hidden=!b;$('solver-form').setAttribute('aria-busy',String(b));}
function stop(){if(worker){worker.terminate();worker=null;}clearTimeout(timer);busy(false);job++;}
function showError(message){$('error-card').textContent=message;$('error-card').hidden=false;$('result-region').hidden=true;$('empty-state').hidden=true;}
function run(){stop();$('error-card').hidden=true;current=null;let q;try{q=query();}catch(e){showError(e.message);return;}if(!q.expression){showError('Escriu una expressi\u00f3 o carrega un exemple.');return;}write('draft-'+mode,q);busy(true);const id=++job;
 try{worker=new Worker('./studio/worker.js');worker.onmessage=e=>{if(e.data.id!==job)return;clearTimeout(timer);worker.terminate();worker=null;busy(false);if(!e.data.ok){showError(e.data.error);return;}current=e.data.result;currentQuery=q;render(current);record(q);};worker.onerror=e=>{stop();showError('No s\u2019ha pogut iniciar el motor. Obre la web publicada amb HTTPS o un servidor local i recarrega.');};worker.postMessage({id,query:q});timer=setTimeout(()=>{stop();showError('S\u2019ha aturat el c\u00e0lcul despr\u00e9s de 10 segons. Redueix l\u2019expressi\u00f3 o l\u2019interval; no s\u2019ha generat cap resultat.');},10000);}catch(e){stop();showError('El motor local no s\u2019ha iniciat: '+e.message);}}
$('cancel-solve').onclick=()=>{stop();toast('C\u00e0lcul cancel\u00b7lat.');};
function render(r){$('result-region').hidden=false;$('empty-state').hidden=true;$('error-card').hidden=true;$('method-badge').textContent=r.method;const textOnly=!r.resultHTML||!/<(?:mi|mn|mo|mfrac|msup)(?:[ >])/.test(r.resultHTML);$('answer').innerHTML=textOnly?'<div class="text-result">'+esc(r.resultText)+'</div>':r.resultHTML;$('answer-approx').textContent=r.numeric!==undefined?'Valor num\u00e8ric de control: '+E.fmt(r.numeric):'';
 const unique=[...new Map((r.restrictions||[]).map(x=>[x.text,x])).values()];$('domain-panel').innerHTML=unique.length?'<section class="domain-card"><strong>RESTRICCIONS DE L\u2019EXPRESSI\u00d3 ORIGINAL</strong><div class="domain-maths">'+unique.map(x=>x.html).join('')+'</div></section>':'';$('warning-panel').innerHTML=r.warnings.length?'<div class="notice">'+r.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')+'</div>':'';
 $('steps-list').innerHTML=r.steps.map((s,i)=>'<details class="step"'+(i===0?' open':'')+'><summary><span class="step-number">'+(i+1)+'</span>'+esc(s.title)+'</summary><div class="step-body"><p>'+esc(s.why||'')+'</p>'+(s.html?'<div class="step-formula">'+s.html+'</div>':'')+'</div></details>').join('')||'<p class="muted">No hi ha desenvolupament simb\u00f2lic disponible per a aquest cas.</p>';
 $('next-step').hidden=r.steps.length<2;$('expand-steps').textContent='Obre tots els passos';$('data-table').innerHTML=r.rows&&r.rows.length?'<table><thead><tr>'+(r.headers||[]).map(t=>'<th>'+esc(t)+'</th>').join('')+'</tr></thead><tbody>'+r.rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'';
 const m=modeInfo(mode);$('teaching-tip').textContent=m.tip;$('teacher-link').href='./docent.html#'+m.teacher;$('graph-card').hidden=!r.plots.length;if(r.plots.length)graph.load(r);window.dispatchEvent(new CustomEvent('studio-solved',{detail:{mode,resultText:r.resultText}}));}
function allSteps(open=true){document.querySelectorAll('.step').forEach(d=>d.open=open);$('expand-steps').textContent=open?'Tanca els passos':'Obre tots els passos';$('next-step').hidden=open||!current||current.steps.length<2;}
$('expand-steps').onclick=()=>allSteps(!!document.querySelector('.step:not([open])'));$('next-step').onclick=()=>{const d=document.querySelector('.step:not([open])');if(d)d.open=true;if(!document.querySelector('.step:not([open])')){$('next-step').hidden=true;$('expand-steps').textContent='Tanca els passos';}};
$('zoom-in').onclick=()=>graph.zoom(.7);$('zoom-out').onclick=()=>graph.zoom(1.4);$('graph-reset').onclick=()=>graph.reset();$('graph-png').onclick=()=>graph.download();
function plainResult(){if(!current)return '';return [modeInfo(current.mode).label,currentQuery.expression,current.resultText,'',...current.steps.flatMap((s,i)=>[(i+1)+'. '+s.title,s.why||'']),'',...current.restrictions.map(r=>'Domini: '+r.text),...current.warnings].join('\n');}
$('copy-result').onclick=async()=>{try{await navigator.clipboard.writeText(plainResult());toast('Resoluci\u00f3 copiada.');}catch(_){toast('El navegador no ha perm\u00e8s copiar. Selecciona el resultat o imprimeix-lo.');}};
let printOpen=[];function beforePrint(){printOpen=[...document.querySelectorAll('.step')].map(d=>d.open);allSteps();graph.draw();}function afterPrint(){document.querySelectorAll('.step').forEach((d,i)=>d.open=printOpen[i]);$('next-step').hidden=!document.querySelector('.step:not([open])');graph.schedule();}
window.addEventListener('beforeprint',beforePrint);window.addEventListener('afterprint',afterPrint);$('print-result').onclick=()=>window.print();
function record(q){history=[{id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),query:q,note:'',date:new Date().toISOString()},...history.filter(x=>JSON.stringify(x.query)!==JSON.stringify(q))].slice(0,30);write('history',history);}
function countSaved(){$('saved-count').textContent=String(saved.length);}
$('save-result').onclick=()=>{if(!currentQuery)return;const old=saved.find(x=>JSON.stringify(x.query)===JSON.stringify(currentQuery));if(old){toast('Aquesta resoluci\u00f3 ja \u00e9s al quadern.');return;}if(saved.length>=100){toast('Quadern ple: exporta una c\u00f2pia i esborra alguna entrada.');return;}const next=[{id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),query:currentQuery,note:'',date:new Date().toISOString()},...saved];if(write('saved',next)){saved=next;countSaved();toast('Desada al quadern.');}};
function showNotebook(){const items=tab==='saved'?saved:history,filter=$('notebook-search').value.toLowerCase();$('notebook-items').textContent='';$('saved-tab').classList.toggle('active',tab==='saved');$('history-tab').classList.toggle('active',tab==='history');const filtered=items.filter(x=>(x.query.expression+' '+x.note+' '+modeInfo(x.query.mode).label).toLowerCase().includes(filter));if(!filtered.length){$('notebook-items').innerHTML='<p class="notebook-empty">'+(filter?'Cap coincid\u00e8ncia.':tab==='saved'?'Encara no hi ha resolucions desades.':'L\u2019historial apareixer\u00e0 quan resolguis una expressi\u00f3.')+'</p>';return;}
 for(const item of filtered){const el=document.createElement('article');el.className='notebook-item';const info=document.createElement('span');info.className='muted';const d=new Date(item.date);info.textContent=modeInfo(item.query.mode).label+' \u00b7 '+(Number.isNaN(d.getTime())?'Data desconeguda':d.toLocaleString('ca'));const code=document.createElement('code');code.textContent=item.query.expression;el.append(info,code);if(tab==='saved'){const note=document.createElement('textarea');note.value=item.note;note.placeholder='Nota docent (es desa autom\u00e0ticament)';note.setAttribute('aria-label','Nota de '+item.query.expression);note.maxLength=2000;note.addEventListener('input',()=>{item.note=note.value;write('saved',saved);});el.append(note);}const buttons=document.createElement('div'),open=document.createElement('button'),del=document.createElement('button');open.className=del.className='secondary';open.textContent='Obre i recalcula';del.textContent='Esborra';open.onclick=()=>{$('notebook-dialog').close();setMode(item.query.mode,item.query);run();};del.onclick=()=>{if(tab==='saved'){saved=saved.filter(x=>x.id!==item.id);write('saved',saved);}else{history=history.filter(x=>x.id!==item.id);write('history',history);}countSaved();showNotebook();};buttons.append(open,del);el.append(buttons);$('notebook-items').append(el);}}
$('notebook-open').onclick=()=>{showNotebook();$('notebook-dialog').showModal();};$('saved-tab').onclick=()=>{tab='saved';showNotebook();};$('history-tab').onclick=()=>{tab='history';showNotebook();};$('notebook-search').oninput=showNotebook;
function downloadText(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('export-data').onclick=()=>{downloadText('mates-estudi-copia-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({app:'mates-estudi',schema:1,version:C.version,exportedAt:new Date().toISOString(),saved,history},null,2),'application/json');toast('C\u00f2pia exportada.');};
$('import-data').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw new Error('El fitxer supera 2 MB.');const data=JSON.parse(await file.text());if(data.app!=='mates-estudi'||data.schema!==1)throw new Error('Format de c\u00f2pia no reconegut.');const s=cleanEntries(data.saved,100),h=cleanEntries(data.history,30);if(!confirm('Substituir les dades d\u2019aquest quadern per la c\u00f2pia? Exporta abans les dades actuals per conservar-les.'))return;if(!write('saved',s)||!write('history',h))throw new Error('No s\u2019ha pogut completar la importaci\u00f3.');saved=s;history=h;countSaved();showNotebook();toast('C\u00f2pia importada.');}catch(err){toast('Importaci\u00f3 rebutjada: '+err.message);}finally{e.target.value='';}};
const help=()=>{if(!$('help-dialog').open)$('help-dialog').showModal();};$('help-open').onclick=help;$('scope-help').onclick=help;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
window.addEventListener('hashchange',()=>{const m=location.hash.slice(1);if(C.modes.some(x=>x.id===m)&&m!==mode)setMode(m);});
buildNav();keyboard('basic');countSaved();const hash=location.hash.slice(1),initial=C.modes.some(x=>x.id===hash)?hash:read('last-mode','eq');setMode(initial);run();
window.StudioApp={load(q,solve=true){setMode(q.mode,validQuery(q));if(solve)run();},run,toast,help,get result(){return current;},get query(){return currentQuery;},get saved(){return saved;},get history(){return history;},graph};
})();
