(function(){'use strict';
window.StudioConfig={version:'2.0.0',modes:[
{id:'eq',group:'a',label:'Equacions',mark:'=',hint:'Equacions en x. Sense igual, es resol expressi\u00f3 = 0.',sample:'x^2-5x+6=0',teacher:'alg',tip:'Anota les restriccions abans de transformar l\u2019equaci\u00f3. Contrasta cada soluci\u00f3 amb els dos membres originals.'},
{id:'inequality',group:'a',label:'Inequacions',mark:'\u2264',hint:'Fraccions racionals amb numerador i denominador fins a grau 2. Usa <, >, <= o >=.',sample:'(x-1)/(x+2)>=0',teacher:'alg',tip:'No multipliquis per un denominador de signe desconegut. Localitza zeros i punts exclosos i construeix la taula de signes.'},
{id:'simplify',group:'a',label:'Simplificar',mark:'\u2248',hint:'Constants exactes, termes semblants i fraccions polin\u00f2miques; conserva el domini original.',sample:'(x^2-1)/(x-1)',teacher:'fun',tip:'Cancel\u00b7lar un factor no recupera un punt que era fora del domini.'},
{id:'expand',group:'a',label:'Desenvolupar',mark:'( )',hint:'Productes i pot\u00e8ncies de polinomis en x fins a grau 12.',sample:'(x+1)^3',teacher:'alg',tip:'Fes visible la distributiva i agrupa per graus. Comprova que l\u2019expressi\u00f3 inicial i la desenvolupada coincideixen.'},
{id:'factor',group:'a',label:'Factoritzar',mark:'\u00d7',hint:'Factors racionals i quadr\u00e0tiques. La factoritzaci\u00f3 pot ser parcial.',sample:'x^3-x',teacher:'alg',tip:'Connecta cada factor lineal amb un zero. Una factoritzaci\u00f3 parcial no demostra irreductibilitat.'},
{id:'system',group:'a',label:'Sistemes lineals',mark:'{',hint:'De 2 a 4 equacions amb x, y, z separades per punt i coma; coeficients num\u00e8rics.',sample:'2x+y=5; x-y=1',teacher:'alg',tip:'Explica qu\u00e8 conserva cada operaci\u00f3 de fila. Interpreta el rang, les variables lliures i les files incompatibles.'},
{id:'derivative',group:'c',label:'Derivades',mark:'f\u2032',hint:'Derivaci\u00f3 simb\u00f2lica amb regles aplicades. Punt de tangent opcional.',sample:'x*exp(x)',teacher:'der',tip:'Identifica suma, producte, quocient o composici\u00f3. Fes dir quina regla s\u2019aplica abans del c\u00e0lcul.'},
{id:'primitive',group:'c',label:'Primitives',mark:'\u222b',hint:'Regles elementals, canvis de variable recognoscibles, parts i algunes fraccions racionals.',sample:'2x*cos(x^2)',teacher:'int',tip:'Derivant el resultat, recuperem l\u2019integrand? La constant C no \u00e9s opcional.'},
{id:'definite',group:'c',label:'Integral definida',mark:'\u222b',hint:'Intervals finits propis: Barrow quan hi ha primitiva; aproximaci\u00f3 num\u00e8rica en la resta.',sample:'sin(x)',teacher:'int',tip:'Decideix si es demana acumulaci\u00f3 amb signe o \u00e0rea. Una integral negativa no \u00e9s una \u00e0rea geom\u00e8trica negativa.'},
{id:'limit',group:'c',label:'L\u00edmits',mark:'lim',hint:'Racionals, l\u00edmits elementals a zero i alguns notables. La taula no substitueix la justificaci\u00f3.',sample:'sin(x)/x',teacher:'lim',tip:'Compara els laterals. Un valor enorme no demostra un l\u00edmit infinit i f(a) no determina el l\u00edmit.'},
{id:'area',group:'g',label:'\u00c0rea entre corbes',mark:'\u25a8',hint:'Integral num\u00e8rica de |f-g| en un interval propi que tu defineixes.',sample:'x^2',teacher:'int',tip:'Localitza on es tallen les corbes i on canvia la funci\u00f3 superior. El valor absolut suma les \u00e0rees dels trams.'},
{id:'study',group:'g',label:'Gr\u00e0fica i estudi',mark:'\u2197',hint:'Derivades, zeros i punts estacionaris candidats en una finestra finita.',sample:'x^3-3x',teacher:'fun',tip:'La finestra \u00e9s una mostra, no tot el domini. Un extrem candidat necessita una justificaci\u00f3.'}
],examples:[
{mode:'eq',expression:'x^2-5x+6=0',label:'Quadr\u00e0tica amb dues arrels'},
{mode:'eq',expression:'2(x-1)=x+5',label:'Equaci\u00f3 lineal'},
{mode:'eq',expression:'x^2+1=0',label:'Sense arrels reals'},
{mode:'eq',expression:'sin(x)=x/2',xmin:'-6',xmax:'6',label:'Cerca num\u00e8rica'},
{mode:'inequality',expression:'(x-1)/(x+2)>=0',label:'Quocient i domini'},
{mode:'inequality',expression:'x^2-5x+6<0',label:'Taula de signes'},
{mode:'inequality',expression:'x^2<=0',label:'Soluci\u00f3 a\u00efllada'},
{mode:'simplify',expression:'(x^2-1)/(x-1)',label:'Simplificar i conservar domini'},
{mode:'simplify',expression:'2/3+5/6',label:'Fraccions exactes'},
{mode:'expand',expression:'(2x-1)^3',label:'Cub d\u2019un binomi'},
{mode:'expand',expression:'(x+2)*(x-3)*(x+1)',label:'Producte de tres factors'},
{mode:'factor',expression:'x^3-x',label:'Factor com\u00fa'},
{mode:'factor',expression:'x^4-5x^2+4',label:'Quatre factors lineals'},
{mode:'system',expression:'2x+y=5; x-y=1',label:'Gauss de dues inc\u00f2gnites'},
{mode:'system',expression:'2x+y-z=8; -3x-y+2z=-11; -2x+y+2z=-3',label:'Sistema 3x3'},
{mode:'system',expression:'x+y=2; 2x+2y=4',label:'Infinites solucions'},
{mode:'derivative',expression:'x*exp(x)',a:'1',label:'Producte i tangent'},
{mode:'derivative',expression:'ln(x^2+1)/x',a:'1',label:'Quocient i cadena'},
{mode:'derivative',expression:'sin(x^2)',order:'2',a:'',label:'Segona derivada'},
{mode:'primitive',expression:'2x*cos(x^2)',label:'Canvi de variable'},
{mode:'primitive',expression:'x*exp(x)',label:'Integraci\u00f3 per parts'},
{mode:'primitive',expression:'1/(1+x^2)',label:'Arctangent'},
{mode:'primitive',expression:'1/x',label:'Logaritme i domini'},
{mode:'definite',expression:'sin(x)',a:'0',b:'pi',label:'Barrow de 0 a pi'},
{mode:'definite',expression:'exp(-x^2)',a:'0',b:'1',label:'Aproximaci\u00f3 num\u00e8rica'},
{mode:'definite',expression:'3x^2-4x+1',a:'0',b:'2',label:'Integral polin\u00f2mica'},
{mode:'limit',expression:'sin(x)/x',a:'0',side:'both',label:'L\u00edmit trigonom\u00e8tric'},
{mode:'limit',expression:'(x^2-1)/(x-1)',a:'1',side:'both',label:'Indeterminaci\u00f3 0/0'},
{mode:'limit',expression:'1/x',a:'0',side:'both',label:'Laterals diferents'},
{mode:'limit',expression:'(1+1/x)^x',a:'inf',side:'both',label:'L\u00edmit exponencial'},
{mode:'area',expression:'x^2',g:'2x',a:'0',b:'2',label:'Par\u00e0bola i recta'},
{mode:'area',expression:'sin(x)',g:'cos(x)',a:'0',b:'pi/2',label:'Canvi de corba superior'},
{mode:'study',expression:'x^3-3x',xmin:'-3',xmax:'3',label:'Monotonia i extrems'},
{mode:'study',expression:'x*exp(-x)',xmin:'-1',xmax:'6',label:'Creixement i decreixement'}
]};
})();
